apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mle-frontend.fullname" . }}-nginx-config
binaryData: {}
data:
  default.conf: |
    {{- tpl .Values.nginxConfig . | nindent 4 }}
  runtime-config.js: |
    window.__APP_CONFIG__ = {
      REACT_APP_BASEURL: {{ .Values.appConfig.REACT_APP_BASEURL | quote }},
      REACT_APP_API_BASEURL: {{ .Values.appConfig.REACT_APP_API_BASEURL | quote }}
    };